### ISSUE TITLE
ArchiveListWidget (and Job) filter "discoverability"

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#131]
Archive tab
- press `ctrl-f` to enable searching.
- no visual clue about this (such as the magnifying glass in the Archive details portion).

I can tackle this in the next few days; just thought I should record it.

**Comment by shinnok** [comment]
On OS X, the filter action is available as a menu item in the system menu bar, but that's certainly not enough indeed. Maybe add it as an action for the right click context menu too? Aside from that, not sure how we can make it more obvious without a header/footer widget or making the filter widget always visible.

**Comment by shinnok** [comment]
Hi Graham,

I pushed a potential fix for the filter discoverability issue. I think it looks good, apart from the duplicate text **Archives** appearing too close to each other, but that might be me being nit-picky. Alternatively I could modify it to something like **Displaying 25/100 archives**, when filtering is enabled. I didn't add the same for Jobs yet.

<img width="665" alt="screen shot 2017-04-05 at 4 27 26 pm" src="https://cloud.githubusercontent.com/assets/544446/24707755/835c3764-1a1d-11e7-93b1-d1d6eca4a84d.png">

**Comment by gperciva** [comment]
I like it!  This certainly satisfies the "discoverability".  :)

I have no particular opinion on adding it to right-click... I'd suggest that we should definitely leave the magnifying glass icon on the screen, but if you'd also like it to be in the right-click menu, I wouldn't object.

Seeing the "Archives" tab and "Archives (3)" doesn't disturb me, but I like the idea of the "25/100" text.  I'm neutral on whether it should be "Displaying 25/100 archives", "Archives (25/100)", or even changing from "Archives (100)" to "Filtered archive list (25/100)" as appropriate.

The only nitpicks I have in mind are tiny visual ones.  On Linux, there's slightly less left/right padding around the "Archives" box than the archive list.  See attached image (perhaps after zooming in).
![gui-padding-left-right](https://cloud.githubusercontent.com/assets/222157/25257420/bd272780-25ec-11e7-9aa0-043ce92066ba.png)

Also, the "selected" magnifying glass looks a bit weird; could we try adding a border of 1 or 2 grey pixels so that the circle doesn't touch the border between grey and white?

**Comment by shinnok** [comment]
I've been using the header for over a week now and it grew on me too. I'll add the same for Jobs and change to "Displaying x/y", that'll make it even more useful. As far as adding it to the right-click menu, I'll think about it over the weekend, but I'm inclined towards not doing it. I'm even thinking about removing the right-click "Backup all" action from the Jobs ListWidget too and add it as an action in the Jobs header. I could do the same for the Refresh button in Archives ListWidget, though it's not that necessary since the user is not really supposed to manually refresh unless he's found something wrong with the list or made a backup using the same key outside of the GUI while the app was running.

I'll fix the visual quirks after that too, for the first issue one I need to adjust the QSS some more. The filter toolbutton has the same problem in Archive contents too, I think a border/content-padding will fix it. Thanks!

**Comment by shinnok** [comment]
Was closed automatically via the commit message. Reopening until you get a peek at the changes.

**Comment by gperciva** [comment]
I like the new approach!  I still see a difference in the padding, though.  Judging from the commit message for 8151b9629ea853461dc0407af4de77f3a6689f71, is this supposed to be fixed?  Or was that fixing a different display thing?

**Comment by shinnok** [comment]
Yep, that's the fix. I converted the widgets to QFrame which is supposed to emulate the box style on the current platform, instead of me trying to manually create the box frames/shadows. On macOS it looks OK now, I need to verify on the other desktops too (need to install icewm).

<img width="459" alt="box-right" src="https://cloud.githubusercontent.com/assets/544446/25577622/2fb48942-2e70-11e7-8069-07ec3bc00023.png">
![box-left](https://cloud.githubusercontent.com/assets/544446/25577623/2fffe112-2e70-11e7-9ff5-e3f0a22c2bf2.png)

**Comment by shinnok** [comment]
Hmm, it looks good on Ubuntu Unity & IceWM. What version of Qt, WM, base system are you using in your first pic? By the looks of it the ArchiveListWidget doesn't have a border at all.

<img width="905" alt="screen shot 2017-05-01 at 1 43 52 pm" src="https://cloud.githubusercontent.com/assets/544446/25578138/7205eb2a-2e74-11e7-928b-bc4214a12051.png">

**Comment by gperciva** [comment]
Fascinating!  I'm on Ubuntu 16.04, so... Qt 5.5.1 and icewm 1.3.8.  I can confirm that when I test with debian Stretch (Qt 5.7, but displayed in an X11 window on my regular desktop, so still icewm 1.3.8 I guess), I see the same results as you.

Here's a pair of screenshots, if you're interested.  The font display is different, but if you switch between them and look at the archive widget, you can definitely see the change.  I'm going to dig into the Qt changelogs.  (apologies for the large size; I maximized the windows so that I'd be certain they were exactly the same size)

Debian stretch:
![gui-debian-stretch](https://cloud.githubusercontent.com/assets/222157/25588260/713f8c0e-2e5c-11e7-9ed6-451331fdc3bb.png)

Ubuntu 16.04:
![gui-ubuntu-16-04](https://cloud.githubusercontent.com/assets/222157/25588261/71502ff0-2e5c-11e7-9d77-a2bbf294c3ad.png)

**Comment by gperciva** [comment]
Update: let's consider this "solved".  If I change into the regular Ubuntu gnome desktop, I see the same nice display that you do.

My normal desktop setup involves a number of customizations I've made over the past decade, and I have no confidence that they're all still valid, especially since icewm is a somewhat "niche" window manager.  I think this is something weird about my system.  :)

When I have some spare time & energy, I'll still poke around a bit, because I'm curious.  But let's focus on other aspects of the GUI now.

**Comment by shinnok** [comment]
Ok, marking this as resolved then. :-)
