### ISSUE TITLE
Clicking on an entry in the Archives tab should display details for it

### ISSUE THREAD

**Issue by shawwn** [Tarsnap/tarsnap-gui#209]
![image](https://user-images.githubusercontent.com/59632/44621514-101c6c80-a86d-11e8-9d12-0992e027ad6b.png)

Currently, to see the details of any given archive, users must click on the entry in the list box and then click on an unlabeled icon (the "i" symbol) in order to see the details.

It might be better to do away with the "i" symbol altogether, and automatically show the details whenever the listbox selection changes.

(Related to this, but I'm not sure it's worth a separate issue: When you click on a listbox item A, and then click on another item B, the UI tries to select every item from A to B inclusive, rather than switching the selection from A to B. It's a bit confusing to try to select a single item, and unexpected since shift isn't held down.)

**Comment by gperciva** [comment]
There's a few ways of seeing archive details:
- click the "i" icon
- double-click on the row
- use the keyboard to navigate to a row, then press enter

I'm reluctant to change the double-click to a single-click, because that would make it harder to select a range of archives.

... speaking of selecting, the "click on A, then B, and unexpectedly see multiple selections" is fixed in #321.  That bug arose from an unexpected combination of factors.
