### ISSUE TITLE
Simulate mode

### ISSUE THREAD

**Issue by shinnok** [Tarsnap/tarsnap-gui#35]
@cperciva @gperciva and others

I implemented a simulate mode, with the help of --dry-run tarsnap cli option. This feature will be released in v0.8.

No new archives will be uploaded to the Tarsnap servers while Simulation is on. The option is available in Settings -> Advanced. Disabling simulation mode or refreshing the Archives list will roll back all new archives and stats. Simulation mode is conveniently flagged while active with a bolt icon close to the busy indicator in the status bar.

<img width="712" alt="screen shot 2015-12-07 at 1 43 31 pm" src="https://cloud.githubusercontent.com/assets/544446/11626070/874f8d66-9ce8-11e5-82d6-8ae4faaccfe0.png">

I need feedback on this. To start you off:
1. Should I disable Simulation mode upon app quit? Currently it persists and must be disabled the same way it was enabled.
2. @cperciva Is there a way of making the cli update the global stats too on -c --print-stats --dry-run (is there any potential for misleading in being able to do so)? The app displays that in Settings->Account page and would provide a nice overall overview of the result of several dry-run actions(complex evaluation of costs), if that would be updated.
3. All other actions like Jobs created, archives deleted will persist. I need an workaround for the fact that the CLI allows for same archive name in this mode. The current buggy behavior of the app in this case is to update the metadata for the already existing archive.

**Comment by cperciva** [comment]
1. Either turn off Simulation mode when the user exits, or have a window pop up when they create an archive.  The worst possible UI failure mode for a backup tool is "user thought they were doing a backup, but in fact nothing happened".

2. Not possible right now, and not very feasible to add.  I agree that it would be useful to let people see what it would cost to run backups over several days (i.e., how much does one archive deduplicate against previous ones) but the way tarsnap works that data is stored in the cache which tells tarsnap which blocks are stored on the server.  If we updated that cache after doing a dry run, we would end up thinking data was stored which wasn't actually there, and consequentially breaking users' archives.

3. I'm not sure exactly what you're getting at here.  There's no way for the client to recognize that an archive already exists with a particular name when doing a dry run, since dry runs never communicate with the server.  But in the GUI you know that you're launching a dry run, so it should be easy for you to handle those differently...?

**Comment by shinnok** [comment]
I'm not sure what Github did here with the comments. They are mixed up apparently? @cperciva

**Comment by gperciva** [comment]
It looks like you replied to @cperciva (via email?), and that somehow got added to his comment.  Weird.

I edited https://github.com/Tarsnap/tarsnap-gui/issues/35#issuecomment-163791994 to clarify what he wrote, and what some else (probably you?) wrote.

**Comment by shinnok** [comment]
I've added a warning message when the app is starting in Simulation mode. I'll leave the functionality as is for the time being, as by reading the mailing lists and other resources, the ability to do dry runs is among the top inquiries into tarsnap.
