### ISSUE TITLE
"Use SI notation" off, but MiB used?

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#42]
In Settings->App-> I do *not* have "Use SI notation" enabled, but my archives and the Settings->Account are shown in MiB.  Using current master 09c08df61f5724203b650ae2058fbd7aa3e2494a, Ubuntu 14.04, Qt 5.2.1.

**Comment by shinnok** [comment]
MiB, mibibyte is IEC which is the default. If you were to enable that checkbox then you'll see SI which would be MB, megabyte.
The potential issue that confused you is that checking that box doesn't apply the change on the fly. The best way to handle this is to warn the user that it's best to restart the app for the change to take place globally.

**Comment by gperciva** [comment]
I can confirm that closing the app and re-starting fixes this.  Two issues:

1) close&restart is really confusing.  Does that apply to everything in Settings, or just this?
2) the command-line app uses SI by default (i.e. when you use `--humanize-numbers`), and http://www.tarsnap.com/GB-why.html makes a good point why that is so.  I suggest that the check-box should be reversed, i.e. "Use IEC byte multipliers".

**Comment by cperciva** [comment]
I agree with Graham -- make SI the default and have an option for switching to IEC units.

**Comment by shinnok** [comment]
@gperciva

1) I think that's the only UI related setting. Updating the UI for this case would imply retroactively re-updating every widget that used it, programatically. Quite the nuisance. What I can easily do:
a) Warn "For this change to take effect the app needs to be restarted." Offering to automagically restart the application is problematic on some/all platforms.
b) Warn and redisplay the GUI, like with reset using setup wizard. Requires some code.

**Comment by gperciva** [comment]
Hmm, maybe my ignorance of Qt is showing.  My first thought was to add:
```
QSettings settings;
int foo = settings.value("app/iec_prefixes", false).toBool();
```
to `QString Utils::humanBytes`, and then something like
```
void ArchiveListItem::paintEvent(QPaintEvent *event)
{
     if(_archive->sizeTotal() != 0)
    {
        QString size = Utils::humanBytes(_archive->sizeTotal(), 99, FIELD_WIDTH);
        detail.prepend(size + "  ");
    }
}
```
(where the `99` would be removed once `Util::humanBytes` was refactored to no longer expect `bool IEC`).

I thought the above code would be cleaner and easy to do, but I must admit that I can't get `ArchiveListItem::paintEvent` to get called (verified with a `printf`).  Am I missing something obvious?

**Comment by shinnok** [comment]
Reimplementing paintEvent() on every widget that uses humanBytes is a bit too much of an "effort" for this small usability gain:
1. Duplicates code.
2. Doing the update on every paintEvent has a performance impact.
3. Forces me to maintain references to _archive's at hand.
4. Makes code a bit harder to maintain, due to 1 and 3.

Why your ArchiveListItem attempt doesn't work is because QListWidgetItem is not a QWidget, but it does have a _widget member on which it applies the ArchiveItemWidget UI. Overriding paintEvent for this case would mean implementing a new class for that _widget with that override. Yet more code to write. ;-)

What I did instead was "overwrite" the old option app/si_prefixes with a new one app/iec_prefixes. This way on app upgrade with the next version the default does become SI and one has to explicitly set use IEC in Settings if desired.

Back to the UI update on the fly, maybe just warning the user to restart is the simplest approach.
